import { PrintwayBaseProduct, RDProject, DataCrawlJob, ScoringWeightsConfig } from "./types";

export const INITIAL_BASE_PRODUCTS: PrintwayBaseProduct[] = [
  {
    sku: "PW-ORN-ACRYLIC-2D",
    name: "Custom Shape Acrylic Ornament (2D)",
    category: "Home & Living / Holiday Decor",
    material: "High-grade 3mm Optix Clear Acrylic",
    baseCost: 3.90,
    estShipping: 4.20,
    leadTimeDays: 2,
    printTechniques: ["UV Direct 2-Side Print", "Laser Precision Cut"],
    printAreas: ["Front & Back (Full Bleed)"],
    image: "https://images.unsplash.com/photo-1543257580-7269da773bf5?w=400&auto=format&fit=crop&q=80",
    factoryLocation: "US",
    inStock: true,
    activeMappedCount: 14,
  },
  {
    sku: "PW-ORN-CERAMIC-ROUND",
    name: "Classic Round Ceramic Ornament (Glossy)",
    category: "Home & Living / Holiday Decor",
    material: "White Ceramic with Glossy Glaze finish",
    baseCost: 3.50,
    estShipping: 4.50,
    leadTimeDays: 2,
    printTechniques: ["Dye Sublimation Full Color"],
    printAreas: ["1-Side or 2-Side"],
    image: "https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=400&auto=format&fit=crop&q=80",
    factoryLocation: "US",
    inStock: true,
    activeMappedCount: 8,
  },
  {
    sku: "PW-APPAREL-HOODIE-G185",
    name: "Gildan 18500 Unisex Heavy Blend Hoodie",
    category: "Apparel / Sweatshirts & Hoodies",
    material: "50% Cotton, 50% Polyester Fleece (8.0 oz)",
    baseCost: 14.80,
    estShipping: 6.99,
    leadTimeDays: 3,
    printTechniques: ["DTG (Direct-to-Garment)", "DTF (Direct-to-Film)"],
    printAreas: ["Front Chest", "Back", "Left Sleeve"],
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=400&auto=format&fit=crop&q=80",
    factoryLocation: "US",
    inStock: true,
    activeMappedCount: 22,
  },
  {
    sku: "PW-APPAREL-TEE-BELLA3001",
    name: "Bella + Canvas 3001 Unisex Jersey T-Shirt",
    category: "Apparel / T-Shirts",
    material: "100% Airlume Combed and Ringspun Cotton",
    baseCost: 7.90,
    estShipping: 4.80,
    leadTimeDays: 2,
    printTechniques: ["DTG Digital Print"],
    printAreas: ["Front", "Back", "Sleeve"],
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=400&auto=format&fit=crop&q=80",
    factoryLocation: "US",
    inStock: true,
    activeMappedCount: 35,
  },
  {
    sku: "PW-DRINK-TUMBLER-20OZ",
    name: "Skinny Tumbler 20oz Stainless Steel Insulated",
    category: "Drinkware / Tumblers",
    material: "Double-wall 18/8 Food Grade Stainless Steel",
    baseCost: 7.20,
    estShipping: 5.50,
    leadTimeDays: 3,
    printTechniques: ["Seamless UV 360 Full Wrap", "Laser Engraving"],
    printAreas: ["Full 360 Wrap Body"],
    image: "https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=400&auto=format&fit=crop&q=80",
    factoryLocation: "US",
    inStock: true,
    activeMappedCount: 19,
  },
  {
    sku: "PW-HOME-WOOD-SIGN-LED",
    name: "Custom Engraved Wood Sign with Warm LED Base",
    category: "Home & Living / Night Lights",
    material: "Natural Beech Wood Stand + 4mm Cast Acrylic",
    baseCost: 8.90,
    estShipping: 5.90,
    leadTimeDays: 4,
    printTechniques: ["Laser Engrave + UV Direct Color"],
    printAreas: ["Full Acrylic Face + Wood Base"],
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&auto=format&fit=crop&q=80",
    factoryLocation: "VN",
    inStock: true,
    activeMappedCount: 11,
  },
  {
    sku: "PW-CANVAS-GALLERY-WRAP",
    name: "Premium Canvas Print 16x20 Gallery Wrap (1.25\")",
    category: "Wall Art / Canvas",
    material: "FSC Certified Pine Wood Stretcher Bars + Archival Poly-Cotton Canvas",
    baseCost: 16.50,
    estShipping: 8.90,
    leadTimeDays: 3,
    printTechniques: ["Giclée Pigment Eco-Solvent Print"],
    printAreas: ["Full Canvas Surface + Mirrored Edges"],
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=400&auto=format&fit=crop&q=80",
    factoryLocation: "US",
    inStock: true,
    activeMappedCount: 6,
  }
];

export const INITIAL_PROJECTS: RDProject[] = [
  {
    id: "proj_q4_2026",
    name: "Q4 Holiday & Christmas 2026 Mega R&D",
    description: "Chiến dịch nghiên cứu toàn diện các sản phẩm Ornament, Sweatshirt, Drinkware quà tặng mùa Giáng sinh và Năm mới tại thị trường US.",
    season: "Q4 Holiday 2026",
    targetMarket: "US",
    status: "RESEARCHING",
    createdAt: "2026-08-10",
    updatedAt: "2026-08-18",
    targetRevenueGoal: 150000,
    niches: [
      {
        id: "niche_dog_mom",
        name: "Personalized Dog Mom & Pet Memorial",
        tag: "dog-mom",
        searchVolumeMonthly: 128000,
        growthRate: "+44%",
        competition: "Medium",
        seasonalityPeak: "Oct - Dec (Holiday Season)",
        productCount: 8,
        avgOpportunityScore: 86.4,
        breakoutKeywords: ["Custom Dog Name Ornament", "Dog Angel Wings Acrylic", "First Christmas with Dog 2026", "Vintage Truck Dog Sweatshirt"],
        topAngles: ["Acrylic Cutout dáng chó kèm tên", "Áo nỉ phong cách Retro 90s in hình thú cưng"]
      },
      {
        id: "niche_grandma_grandkids",
        name: "Grandma's Little Angels & Family Heart",
        tag: "grandma-family",
        searchVolumeMonthly: 94000,
        growthRate: "+32%",
        competition: "Low",
        seasonalityPeak: "Nov - Dec",
        productCount: 6,
        avgOpportunityScore: 82.1,
        breakoutKeywords: ["Grandma Garden Birth Flower Ornament", "Grandpa's Favorite Catch Sweatshirt", "Grandkids Names Acrylic Heart"],
        topAngles: ["Cá nhân hóa từ 1 đến 12 tên cháu nhỏ", "Hiệu ứng hoa tháng sinh màu nước (Watercolor Birth Flower)"]
      },
      {
        id: "niche_first_home_couple",
        name: "First Christmas in Our New Home 2026",
        tag: "first-home",
        searchVolumeMonthly: 76000,
        growthRate: "+28%",
        competition: "High",
        seasonalityPeak: "Nov - Dec",
        productCount: 4,
        avgOpportunityScore: 78.5,
        breakoutKeywords: ["New Home Key Shape Ornament", "Our First Home Address Ornament 2026", "Housewarming Couple Keepsake"],
        topAngles: ["Khắc hình vẽ phác thảo ngôi nhà + Địa chỉ", "Chất liệu Acrylic trong suốt viền gỗ"]
      },
      {
        id: "niche_teacher_nurse",
        name: "Appreciation Gifts (Teacher & Healthcare)",
        tag: "appreciation-worker",
        searchVolumeMonthly: 52000,
        growthRate: "+18%",
        competition: "Medium",
        seasonalityPeak: "Dec - Jan",
        productCount: 3,
        avgOpportunityScore: 71.2,
        breakoutKeywords: ["Teacher Crayon Ornament 2026", "Nurse Stethoscope Heart Tumbler", "Educator Christmas Thank You"],
        topAngles: ["Cốc giữ nhiệt 20oz in tên cô giáo/y tá", "Ornament hình bảng phấn mini"]
      }
    ],
    products: [
      {
        id: "prod_001",
        projectId: "proj_q4_2026",
        nicheTag: "dog-mom",
        title: "Personalized Dog Breed Christmas Acrylic Ornament 2026, Custom Pet Name Angel Wings Keepsake",
        platform: "Etsy",
        sourceUrl: "https://etsy.com/listing/custom-dog-breed-acrylic-ornament-2026",
        imageUrl: "https://images.unsplash.com/photo-1543257580-7269da773bf5?w=500&auto=format&fit=crop&q=80",
        sellerName: "HeartCraftKeepsakes",
        retailPrice: 19.99,
        estMonthlySales: 1850,
        estMonthlyRevenue: 36981,
        reviewCount: 420,
        rating: 4.9,
        bsrOrRank: "#1 Best Seller in Holiday Ornaments",
        mappedBaseSku: "PW-ORN-ACRYLIC-2D",
        matchConfidence: 0.96,
        overallScore: 89.2,
        decision: "RECOMMENDED",
        groupScores: {
          production: 9.4,
          financial: 8.8,
          market: 8.7
        },
        metrics: [
          { name: "Production Fit", group: "production", score: 9.8, weight: 0.10, rawValue: "100% khớp xưởng Printway UV Cut", description: "Xưởng US có sẵn phôi Acrylic 3mm và máy cắt laser" },
          { name: "Production Time", group: "production", score: 9.2, weight: 0.05, rawValue: "2 ngày sản xuất (US)", description: "Lead time nhanh vượt trội so với đối thủ ship từ TQ" },
          { name: "Seasonality Fit", group: "production", score: 9.5, weight: 0.10, rawValue: "Đúng điểm rơi Q4", description: "Lượng tìm kiếm tăng vọt từ tháng 9 đến 24/12" },
          { name: "Personalization Level", group: "production", score: 9.0, weight: 0.05, rawValue: "Tên + 120 dáng chó", description: "Khách hàng dễ điền form cá nhân hóa" },
          { name: "Potential Revenue", group: "financial", score: 8.6, weight: 0.15, rawValue: "$36,900/tháng", description: "Quy mô doanh thu thị trường lớn" },
          { name: "Profit Margin", group: "financial", score: 9.0, weight: 0.20, rawValue: "44.5% Net Margin", description: "Giá bán $19.99, chi phí gốc xưởng + ship chỉ $8.10" },
          { name: "Market Demand", group: "market", score: 9.2, weight: 0.15, rawValue: "128K Search/mo", description: "Lượng tìm kiếm từ khóa ngách tăng liên tục" },
          { name: "Growth Rate", group: "market", score: 8.8, weight: 0.10, rawValue: "+44% MoM", description: "Tốc độ viral trên TikTok Shop và Pinterest" },
          { name: "Competition Level", group: "market", score: 7.8, weight: 0.10, rawValue: "Medium (Dễ tạo khác biệt bằng artwork)", description: "Cạnh tranh ở mức vừa phải nếu làm artwork chi tiết" }
        ],
        estNetProfit: 8.90,
        estProfitMargin: 44.5,
        aiSummary: "Sản phẩm chiến lược đạt chuẩn 🟢 NÊN SẢN XUẤT NGAY. Khả năng gia công tại Printway hoàn hảo với chi phí cực thấp, lợi nhuận ròng gần $9/đơn hàng.",
        designAngle: "Tập trung bổ sung các giống chó hiếm như French Bulldog lông vện, Golden Doodle đeo nón Noel đỏ.",
        optimalLaunchWindow: "Tuần đầu tháng 10/2026 (Để test camp và tối ưu SEO trước Black Friday)",
        addedAt: "2026-08-15"
      },
      {
        id: "prod_002",
        projectId: "proj_q4_2026",
        nicheTag: "dog-mom",
        title: "Vintage Retro Dog Mom Christmas Sweatshirt, Custom Dog Ear Outline Embroidered Style Graphic",
        platform: "Amazon",
        sourceUrl: "https://amazon.com/dp/B0CUSTOMSWEAT26",
        imageUrl: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=500&auto=format&fit=crop&q=80",
        sellerName: "PawsomeApparelUSA",
        retailPrice: 38.99,
        estMonthlySales: 920,
        estMonthlyRevenue: 35870,
        reviewCount: 310,
        rating: 4.8,
        bsrOrRank: "BSR #820 in Clothing & Novelty",
        mappedBaseSku: "PW-APPAREL-HOODIE-G185",
        matchConfidence: 0.92,
        overallScore: 84.8,
        decision: "RECOMMENDED",
        groupScores: {
          production: 8.6,
          financial: 8.7,
          market: 8.2
        },
        metrics: [
          { name: "Production Fit", group: "production", score: 8.8, weight: 0.10, rawValue: "In DTG/DTF trên áo nỉ G185", description: "Xưởng US in tốt chất lượng màu cao" },
          { name: "Production Time", group: "production", score: 8.5, weight: 0.05, rawValue: "3 ngày làm việc", description: "Thời gian xử lý tốt trong mùa lễ" },
          { name: "Seasonality Fit", group: "production", score: 9.2, weight: 0.10, rawValue: "Áo nỉ mùa đông Q4", description: "Mùa đông thời tiết lạnh đẩy nhu cầu áo nỉ lên đỉnh điểm" },
          { name: "Personalization Level", group: "production", score: 8.0, weight: 0.05, rawValue: "Tên cún + Tai vẽ nét đơn", description: "Phong cách tối giản Minimalism" },
          { name: "Potential Revenue", group: "financial", score: 8.5, weight: 0.15, rawValue: "$35,800/tháng", description: "AOV cao ($38 - $45)" },
          { name: "Profit Margin", group: "financial", score: 8.9, weight: 0.20, rawValue: "36.8% ($14.35 Net)", description: "Base cost $14.80 + Ship $6.99" },
          { name: "Market Demand", group: "market", score: 8.4, weight: 0.15, rawValue: "88K Search/mo", description: "Từ khóa Dog Mom Hoodie có lượng fan cứng đông đảo" },
          { name: "Growth Rate", group: "market", score: 8.0, weight: 0.10, rawValue: "+35% YoY", description: "Xu hướng bền vững qua các năm" },
          { name: "Competition Level", group: "market", score: 8.0, weight: 0.10, rawValue: "Medium-High", description: "Cần chú trọng mockup chân thực và video TikTok" }
        ],
        estNetProfit: 14.35,
        estProfitMargin: 36.8,
        aiSummary: "Mẫu áo nỉ AOV cao, mang lại dòng tiền và biên lợi nhuận tuyệt đối lớn ($14.35/áo). Đề xuất đưa vào danh mục chiến lược.",
        designAngle: "Đường nét tai chó vẽ tay phối màu cát (Sand) và màu Forest Green hot trend.",
        optimalLaunchWindow: "15/10/2026 - Đón đầu đợt mua sắm Early Bird",
        addedAt: "2026-08-16"
      },
      {
        id: "prod_003",
        projectId: "proj_q4_2026",
        nicheTag: "grandma-family",
        title: "Grandkids Spoiled Here Acrylic Night Light with Wood Stand, Personalized Nana Gift",
        platform: "TikTok Shop",
        sourceUrl: "https://tiktok.com/@craftyfamily/video/nightlight78",
        imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500&auto=format&fit=crop&q=80",
        sellerName: "GlowWoodGifts",
        retailPrice: 29.99,
        estMonthlySales: 1100,
        estMonthlyRevenue: 32989,
        reviewCount: 195,
        rating: 4.9,
        bsrOrRank: "Viral Trend TikTok (#NanaGift 8.4M views)",
        mappedBaseSku: "PW-HOME-WOOD-SIGN-LED",
        matchConfidence: 0.95,
        overallScore: 81.5,
        decision: "RECOMMENDED",
        groupScores: {
          production: 7.9,
          financial: 8.6,
          market: 8.1
        },
        metrics: [
          { name: "Production Fit", group: "production", score: 8.0, weight: 0.10, rawValue: "Đế gỗ LED xưởng VN/US", description: "Có thể sản xuất tại xưởng VN hoặc xưởng US" },
          { name: "Production Time", group: "production", score: 7.5, weight: 0.05, rawValue: "4 ngày (Xưởng VN)", description: "Cần chú ý deadline ship quốc tế nếu gia công tại VN" },
          { name: "Seasonality Fit", group: "production", score: 8.8, weight: 0.10, rawValue: "Quà tặng Noel & Lễ Tạ Ơn", description: "Món quà cảm xúc rất chuộng trong dịp gia đình sum họp" },
          { name: "Personalization Level", group: "production", score: 8.5, weight: 0.05, rawValue: "Tên bà + Tên các cháu", description: "Tối đa 10 tên trên các trái tim Acrylic" },
          { name: "Potential Revenue", group: "financial", score: 8.2, weight: 0.15, rawValue: "$32,900/tháng", description: "Viral mạnh trên video ngắn" },
          { name: "Profit Margin", group: "financial", score: 9.0, weight: 0.20, rawValue: "42.0% ($12.60 Net)", description: "Base cost $8.90 + Ship $5.90" },
          { name: "Market Demand", group: "market", score: 8.2, weight: 0.15, rawValue: "70K Search/mo", description: "Nhu cầu mua tặng bà (Nana/Gigi/Mimi) luôn cao" },
          { name: "Growth Rate", group: "market", score: 8.5, weight: 0.10, rawValue: "+48% Viral Growth", description: "Video unboxing quà của bà đạt triệu views" },
          { name: "Competition Level", group: "market", score: 7.5, weight: 0.10, rawValue: "Low-Medium", description: "Ít đối thủ có sẵn đế đèn LED ấm chất lượng cao" }
        ],
        estNetProfit: 12.60,
        estProfitMargin: 42.0,
        aiSummary: "Sản phẩm Decor ánh sáng mang tính cảm xúc cao, rất thích hợp chạy Ads TikTok và Reels. Printway có thể đáp ứng tốt.",
        designAngle: "Hình trái tim trung tâm ghi 'Grandma's Garden' với mỗi bông hoa đại diện cho 1 cháu.",
        optimalLaunchWindow: "Cuối tháng 10/2026",
        addedAt: "2026-08-17"
      },
      {
        id: "prod_004",
        projectId: "proj_q4_2026",
        nicheTag: "first-home",
        title: "Our First Christmas in Our New Home 2026 Wooden Map Key Ornament, Laser Cut Address",
        platform: "Etsy",
        sourceUrl: "https://etsy.com/listing/first-home-key-ornament",
        imageUrl: "https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=500&auto=format&fit=crop&q=80",
        sellerName: "MapleCraftHome",
        retailPrice: 16.99,
        estMonthlySales: 540,
        estMonthlyRevenue: 9174,
        reviewCount: 88,
        rating: 4.7,
        mappedBaseSku: "PW-ORN-CERAMIC-ROUND",
        matchConfidence: 0.68,
        overallScore: 64.2,
        decision: "REVIEW_REQUIRED",
        groupScores: {
          production: 6.2,
          financial: 6.8,
          market: 6.5
        },
        metrics: [
          { name: "Production Fit", group: "production", score: 6.0, weight: 0.10, rawValue: "Gỗ 2 lớp cắt thủ công", description: "Printway hiện mạnh về Acrylic và Gốm hơn là ghép gỗ thủ công nhiều lớp" },
          { name: "Production Time", group: "production", score: 7.0, weight: 0.05, rawValue: "3 ngày", description: "Mức trung bình" },
          { name: "Seasonality Fit", group: "production", score: 8.0, weight: 0.10, rawValue: "Chỉ bán tốt 2 tháng", description: "Vòng đời sản phẩm ngắn hạn theo năm 2026" },
          { name: "Personalization Level", group: "production", score: 8.5, weight: 0.05, rawValue: "Địa chỉ nhà + Tên cặp đôi", description: "Form điền phức tạp" },
          { name: "Potential Revenue", group: "financial", score: 6.5, weight: 0.15, rawValue: "$9,100/tháng", description: "Quy mô vừa phải" },
          { name: "Profit Margin", group: "financial", score: 7.0, weight: 0.20, rawValue: "28.5%", description: "Biên lợi nhuận thấp do giá bán cạnh tranh $16.99" },
          { name: "Market Demand", group: "market", score: 7.0, weight: 0.15, rawValue: "45K Search/mo", description: "Cầu ổn định" },
          { name: "Growth Rate", group: "market", score: 6.2, weight: 0.10, rawValue: "+12%", description: "Tăng trưởng bình thường" },
          { name: "Competition Level", group: "market", score: 6.0, weight: 0.10, rawValue: "High (Quá nhiều shop bán cùng 1 mẫu)", description: "Độ bão hòa listing cao" }
        ],
        estNetProfit: 4.84,
        estProfitMargin: 28.5,
        aiSummary: "Sản phẩm ở mức 🟡 CẦN XEM XÉT. Nên chuyển đổi phôi sang Acrylic 2D trong suốt in giả vân gỗ để giảm giá thành gia công tại Printway và tăng biên lợi nhuận lên > 40%.",
        designAngle: "Đổi sang phôi Acrylic giả lập chìa khóa vàng phối nền hoa tuyết trong suốt.",
        optimalLaunchWindow: "Tháng 11/2026",
        addedAt: "2026-08-17"
      }
    ]
  },
  {
    id: "proj_spring_2027",
    name: "Spring & Mother's Day 2027 Early Discovery",
    description: "Nghiên cứu sớm các dòng sản phẩm quà tặng Ngày Của Mẹ và mùa Xuân 2027 (Tumbler, T-Shirt, Acrylic Flowers).",
    season: "Spring & Mother's Day 2027",
    targetMarket: "US",
    status: "DRAFT",
    createdAt: "2026-08-14",
    updatedAt: "2026-08-18",
    targetRevenueGoal: 80000,
    niches: [
      {
        id: "niche_mom_birth_flower",
        name: "Birth Flower Bouquet for Mom",
        tag: "mom-flower",
        searchVolumeMonthly: 85000,
        growthRate: "+52%",
        competition: "Low",
        seasonalityPeak: "March - May (Mother's Day)",
        productCount: 4,
        avgOpportunityScore: 88.0,
        breakoutKeywords: ["Mom's Garden Tumbler 20oz", "Personalized Birth Month Flower Plaque", "Grandma's Bunch of Flowers Shirt"],
        topAngles: ["Cốc giữ nhiệt UV 360 độ in hoa tháng sinh của các con"]
      }
    ],
    products: []
  }
];

export const INITIAL_CRAWL_JOBS: DataCrawlJob[] = [
  {
    id: "job_01",
    projectId: "proj_q4_2026",
    projectName: "Q4 Holiday & Christmas 2026 Mega R&D",
    nicheTag: "dog-mom",
    platform: "Etsy",
    keyword: "custom dog christmas acrylic ornament",
    targetCount: 100,
    scrapedCount: 100,
    status: "COMPLETED",
    createdAt: "2026-08-18 14:20",
    speed: "25 items/s"
  },
  {
    id: "job_02",
    projectId: "proj_q4_2026",
    projectName: "Q4 Holiday & Christmas 2026 Mega R&D",
    nicheTag: "grandma-family",
    platform: "Amazon",
    keyword: "personalized grandma christmas sweatshirt",
    targetCount: 80,
    scrapedCount: 65,
    status: "RUNNING",
    createdAt: "2026-08-18 16:05",
    speed: "12 items/s"
  },
  {
    id: "job_03",
    projectId: "proj_spring_2027",
    projectName: "Spring & Mother's Day 2027 Early Discovery",
    nicheTag: "mom-flower",
    platform: "TikTok Shop",
    keyword: "birth flower tumbler mom gift",
    targetCount: 50,
    scrapedCount: 50,
    status: "COMPLETED",
    createdAt: "2026-08-18 11:30",
    speed: "18 items/s"
  }
];

export const DEFAULT_SCORING_WEIGHTS: ScoringWeightsConfig = {
  production_fit: 0.10,
  production_time: 0.05,
  seasonality_fit: 0.10,
  personalization_level: 0.05,
  potential_revenue: 0.15,
  profit_margin: 0.20,
  market_demand: 0.15,
  growth_rate: 0.10,
  competition_level: 0.10,
  recommendedThreshold: 70,
  reviewThreshold: 50
};
